import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ChatLogo from './components/ChatLogo';

const inter = Inter({ subsets: ['latin'] });

const btnClass = 'bg-blue-500';
console.log('btnClass');

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-primaryBlue ${inter.className}`}>
        <header>
          <ChatLogo />
        </header>
        {children}
      </body>
    </html>
  );
}
